### ISSUE TITLE
Quesetion on loading taxonomies

### ISSUE THREAD

**Issue by yuenchingshen** [dib-lab/2022-database-covers#8]
in simple-use-case.md:
For added linux fun!, let's try to create the sqldb to fully copy Titus' bash command. If we look at the [sourmash documentation](https://sourmash.readthedocs.io/en/latest/databases-advanced.html#storing-taxonomies), we can narrow in on the command to do this! Running `sourmash tax prepare -h` will give us guidance to running this sub-command as well.

Using the linked lineage file...
```
sourmash tax prepare --taxonomy-csv ./gtdb-rs214.lineages.csv -F sql -o gtdb-rs214.lineages.sqldb
```

Doesn't work!!!
```
== This is sourmash version 4.8.5. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loading taxonomies...
ERROR while loading taxonomies!
cannot read taxonomy assignments from 'gtdb-rs214.lineages.csv': 'gtdb-rs214.lineages.csv' does not exist
```

Well, that's okay because we know the absolute path to the file anyway.

```
sourmash tax prepare --taxonomy-csv /group/ctbrowngrp/sourmash-db/gtdb-rs214/gtdb-rs214.lineages.csv -F sql -o gtdb-rs214.lineages.sqldb
```

Yay, we get the correct output:
```
== This is sourmash version 4.8.5. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loading taxonomies...
...loaded 402709 entries.
saving to 'gtdb-rs214.lineages.sqldb', format sql...
done!
```
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

I followed the guide, and tried using the absolute path/ location of the file in my computer, and it did not work
```
(base) yc22@farm:~/2022-database-covers$ ls
README.md	    gtdb-rs214.lineages.csv  make-pangenome-sketches.py  run.sh
gtdb-rs214-k21.zip  make-db-cover.py	     make-pangenome.sh		 simple-use-case.md
(base) yc22@farm:~/2022-database-covers$ pwd
/home/yc22/2022-database-covers
(base) yc22@farm:~/2022-database-covers$ sourmash tax prepare --taxonomy-csv /home/yc22/2022-database-covers/gtdb-rs214.lineages.csv -F sql -o gtdb-rs214.lineages.sqldb
sourmash: command not found
```

I was thinking maybe I was in the wrong branch, cause it said sourmash command not found, so I changed directory and tried again. But it still did not work.
```
(base) yc22@farm:~$ ls
2022-database-covers	    miniforge3	      sourmash
Miniforge3-Linux-x86_64.sh  pangenomeproject  spacegraphcats
(base) yc22@farm:~$ sourmash tax prepare --taxonomy-csv /group/ctbrowngrp/sourmash-db/gtdb-rs214/gtdb-rs214.lineages.csv -F sql -o gtdb-rs214.lineages.sqldb
sourmash: command not found
```
I would need some help on how to fix the code and load the taxonomies.

**Comment by yuenchingshen** [comment]
@ccbaumler hi Colton, I have a question on loading taxonomies

**Comment by ccbaumler** [comment]
Hi @yuenchingshen, if you look at your command line you will see `(base)` in the start of each line:

> ```
> (base) yc22@farm:~$ sourmash tax prepare --taxonomy-csv /group/ctbrowngrp/sourmash-db/gtdb-rs214/gtdb-rs214.lineages.csv -F sql -o gtdb-rs214.lineages.sqldb 
> sourmash: command not found
> ```

Also, standard convention for quoting text is to place `>` at the start of each line to create the indented text. It makes it easier to read. :)

**Comment by ccbaumler** [comment]
Hi @yuenchingshen, if you look at your command line you will see `(base)` in the start of each line:

> ```
> (base) yc22@farm:~$ sourmash tax prepare --taxonomy-csv /group/ctbrowngrp/sourmash-db/gtdb-rs214/gtdb-rs214.lineages.csv -F sql -o gtdb-rs214.lineages.sqldb 
> sourmash: command not found
> ```

You are in your base conda environment. You need to activate your sourmash environment to run sourmash. 

Also! When quoting text in markdown, it is common practice to use `>` at the beginning of the line. This creates the indent and makes the documents easier to read.
